namespace Task_1_1
{
    internal class Admin : Client
    {
        public Admin(int id, string role, int adminId, int personId, string adress, string clientName, int accountNum)
            : base(id, personId, adress, clientName, accountNum)
        {
            this.role = role;
            this.adminId = this.adminId;
        }

        private string role;
        private int adminId;

        public void AddClient(Storage storage, Client client)
        {
            storage.AddToClientList(client);
        }

        public void RemoveClient(Storage storage, Client client)
        {
            storage.RemoveClient(client);
        }

        public string ViewTransactions(Storage storage)
        {
            var storageList = storage.GetTransactionList();

            string text = "";
            for (int i = 0; i < storageList.Count; i++)
            {
                text += storageList[i].get_transaction_details() + "\n";
            }
            return text;
        }

        public string GenerateReport(Storage storage)
        {
            var storageList = storage.GetTransactionList();
            string text = $"Report generated by admin ID:{adminId} \n";
            for (int i = 0; i < storageList.Count; i++)
            {
                text += storageList[i].get_transaction_details() + "\n";
            }
            return text;
        }
    }
}
