using System;

namespace Task_1_1
{
	internal class Admin : Person
	{
		public Admin(string role,int admin_id,int person_id, string adress, string client_name, int account_num)
			: base(person_id, adress, client_name, account_num)
        {
			this.role = role;
			this.admin_id = admin_id;
		}

		private string role;
		private int admin_id;

		public void add_client(Storage storage, Person person)
		{
			storage.add_to_clientlist(person);
		}

		public void remove_client(Storage storage, Person person)
		{
            storage.remove_client(person);
        }

		public string view_transactions(Storage storage)
		{
			var storage_list = storage.get_transactionlist();

            string text = "";
			for (int i = 0; i < storage_list.Count; i++)
			{
				text += storage_list[i].get_transaction_details() + "\n";
			}
			return text;
		}

		public string generate_report(Storage storage)
		{
			var storage_list = storage.get_transactionlist();
            string text = $"Report generated by admin ID:{admin_id} \n";
            for (int i = 0; i < storage_list.Count; i++)
            {
                text += storage_list[i].get_transaction_details() + "\n";
            }
            return text;
        }
	}
}
